using eBolnicaAPI.Models.Settings;
using QuestPDF.Fluent;
using QuestPDF.Helpers;
using QuestPDF.Infrastructure;

namespace eBolnicaAPI.PdfComponents
{
    /// <summary>
    /// Professional PDF footer component with page numbers and confidentiality notice
    /// </summary>
    public class FooterComponent : IComponent
    {
        private readonly PdfGenerationSettings _settings;

        public FooterComponent(PdfGenerationSettings settings)
        {
            _settings = settings;
        }

        public void Compose(IContainer container)
        {
            container
                .Column(column =>
                {
                    // Separator line
                    column.Item()
                        .PaddingBottom(10)
                        .LineHorizontal(0.5f)
                        .LineColor(Colors.Grey.Lighten2);

                    // Footer content
                    column.Item()
                        .Row(row =>
                        {
                            // Left: Confidentiality notice
                            row.RelativeItem()
                                .Text("CONFIDENTIAL - For internal use only")
                                .FontSize(8)
                                .Italic()
                                .FontColor(Colors.Grey.Medium);

                            // Center: Generation info
                            row.RelativeItem()
                                .AlignCenter()
                                .Text("Generated by Pharmacy Module v1.0")
                                .FontSize(8)
                                .FontColor(Colors.Grey.Medium);

                            // Right: Page numbers
                            if (_settings.IncludePageNumbers)
                            {
                                row.RelativeItem()
                                    .AlignRight()
                                    .Text(text =>
                                    {
                                        text.Span("Page ");
                                        text.CurrentPageNumber().FontColor(PharmacyPdfTheme.PrimaryColor).FontSize(9);
                                        text.Span(" of ");
                                        text.TotalPages().FontColor(PharmacyPdfTheme.PrimaryColor).FontSize(9);
                                    });
                            }
                        });

                    // Copyright/legal line
                    column.Item()
                        .PaddingTop(5)
                        .Text($"© {DateTime.Now.Year} Pharmacy Management System. All rights reserved.")
                        .FontSize(7)
                        .AlignCenter()
                        .FontColor(Colors.Grey.Medium);
                });
        }
    }
}
