// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using eBolnicaAPI.Data;

#nullable disable

namespace eBolnicaAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260113164348_Update1")]
    partial class Update1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("eBolnicaAPI.Models.Entities.AppUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LicenseNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("UserType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "a1",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "fixed-guid-3",
                            Email = "admin@gmail.com",
                            EmailConfirmed = true,
                            FirstName = "Admin",
                            LastName = "User",
                            LockoutEnabled = true,
                            NormalizedEmail = "ADMIN@GMAIL.COM",
                            NormalizedUserName = "ADMIN@GMAIL.COM",
                            PhoneNumber = "061000000",
                            PhoneNumberConfirmed = true,
                            SecurityStamp = "fixed-guid-3",
                            TwoFactorEnabled = false,
                            UserName = "admin@gmail.com",
                            UserType = "Admin"
                        },
                        new
                        {
                            Id = "d1",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "fixed-guid-1",
                            Email = "marko@gmail.com",
                            EmailConfirmed = false,
                            FirstName = "Marko",
                            LastName = "Marković",
                            LicenseNumber = "L1",
                            LockoutEnabled = true,
                            NormalizedEmail = "MARKO@GMAIL.COM",
                            NormalizedUserName = "MARKO@GMAIL.COM",
                            PhoneNumber = "061100100",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "fixed-guid-2",
                            TwoFactorEnabled = false,
                            UserName = "marko@gmail.com",
                            UserType = "Doctor"
                        },
                        new
                        {
                            Id = "d2",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "fixed-guid-1",
                            Email = "senad@gmail.com",
                            EmailConfirmed = false,
                            FirstName = "Senad",
                            LastName = "Husić",
                            LicenseNumber = "L2",
                            LockoutEnabled = true,
                            NormalizedEmail = "SENAD@GMAIL.COM",
                            NormalizedUserName = "SENAD@GMAIL.COM",
                            PhoneNumber = "061100101",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "fixed-guid-2",
                            TwoFactorEnabled = false,
                            UserName = "senad@gmail.com",
                            UserType = "Doctor"
                        },
                        new
                        {
                            Id = "d3",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "fixed-guid-1",
                            Email = "petar@gmail.com",
                            EmailConfirmed = false,
                            FirstName = "Petar",
                            LastName = "Petrović",
                            LicenseNumber = "L3",
                            LockoutEnabled = true,
                            NormalizedEmail = "PETAR@GMAIL.COM",
                            NormalizedUserName = "PETAR@GMAIL.COM",
                            PhoneNumber = "061100102",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "fixed-guid-2",
                            TwoFactorEnabled = false,
                            UserName = "petar@gmail.com",
                            UserType = "Doctor"
                        },
                        new
                        {
                            Id = "p1",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "fixed-guid-1",
                            Email = "ismet@gmail.com",
                            EmailConfirmed = false,
                            FirstName = "Ismet",
                            LastName = "Horo",
                            LockoutEnabled = true,
                            NormalizedEmail = "ISMET@GMAIL.COM",
                            NormalizedUserName = "ISMET@GMAIL.COM",
                            PhoneNumber = "061100103",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "fixed-guid-2",
                            TwoFactorEnabled = false,
                            UserName = "ismet@gmail.com",
                            UserType = "Patient"
                        },
                        new
                        {
                            Id = "p2",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "fixed-guid-1",
                            Email = "elon@gmail.com",
                            EmailConfirmed = false,
                            FirstName = "Elon",
                            LastName = "Musk",
                            LockoutEnabled = true,
                            NormalizedEmail = "ELON@GMAIL.COM",
                            NormalizedUserName = "ELON@GMAIL.COM",
                            PhoneNumber = "061100104",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "fixed-guid-2",
                            TwoFactorEnabled = false,
                            UserName = "elon@gmail.com",
                            UserType = "Patient"
                        },
                        new
                        {
                            Id = "p3",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "fixed-guid-1",
                            Email = "peter@gmail.com",
                            EmailConfirmed = false,
                            FirstName = "Peter",
                            LastName = "Griffin",
                            LockoutEnabled = true,
                            NormalizedEmail = "PETER@GMAIL.COM",
                            NormalizedUserName = "PETER@GMAIL.COM",
                            PhoneNumber = "061100105",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "fixed-guid-2",
                            TwoFactorEnabled = false,
                            UserName = "peter@gmail.com",
                            UserType = "Patient"
                        },
                        new
                        {
                            Id = "p4",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "fixed-guid-1",
                            Email = "ana@gmail.com",
                            EmailConfirmed = false,
                            FirstName = "Ana",
                            LastName = "Jovanović",
                            LockoutEnabled = true,
                            NormalizedEmail = "ANA@GMAIL.COM",
                            NormalizedUserName = "ANA@GMAIL.COM",
                            PhoneNumber = "061100106",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "fixed-guid-2",
                            TwoFactorEnabled = false,
                            UserName = "ana@gmail.com",
                            UserType = "Patient"
                        },
                        new
                        {
                            Id = "p5",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "fixed-guid-1",
                            Email = "marko.patient@gmail.com",
                            EmailConfirmed = false,
                            FirstName = "Marko",
                            LastName = "Nikolić",
                            LockoutEnabled = true,
                            NormalizedEmail = "MARKO.PATIENT@GMAIL.COM",
                            NormalizedUserName = "MARKO.PATIENT@GMAIL.COM",
                            PhoneNumber = "061100107",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "fixed-guid-2",
                            TwoFactorEnabled = false,
                            UserName = "marko.patient@gmail.com",
                            UserType = "Patient"
                        },
                        new
                        {
                            Id = "p6",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "fixed-guid-1",
                            Email = "sara@gmail.com",
                            EmailConfirmed = false,
                            FirstName = "Sara",
                            LastName = "Stojanović",
                            LockoutEnabled = true,
                            NormalizedEmail = "SARA@GMAIL.COM",
                            NormalizedUserName = "SARA@GMAIL.COM",
                            PhoneNumber = "061100108",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "fixed-guid-2",
                            TwoFactorEnabled = false,
                            UserName = "sara@gmail.com",
                            UserType = "Patient"
                        },
                        new
                        {
                            Id = "p7",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "fixed-guid-1",
                            Email = "nikola@gmail.com",
                            EmailConfirmed = false,
                            FirstName = "Nikola",
                            LastName = "Popović",
                            LockoutEnabled = true,
                            NormalizedEmail = "NIKOLA@GMAIL.COM",
                            NormalizedUserName = "NIKOLA@GMAIL.COM",
                            PhoneNumber = "061100109",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "fixed-guid-2",
                            TwoFactorEnabled = false,
                            UserName = "nikola@gmail.com",
                            UserType = "Patient"
                        },
                        new
                        {
                            Id = "p8",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "fixed-guid-1",
                            Email = "jovana@gmail.com",
                            EmailConfirmed = false,
                            FirstName = "Jovana",
                            LastName = "Milošević",
                            LockoutEnabled = true,
                            NormalizedEmail = "JOVANA@GMAIL.COM",
                            NormalizedUserName = "JOVANA@GMAIL.COM",
                            PhoneNumber = "061100110",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "fixed-guid-2",
                            TwoFactorEnabled = false,
                            UserName = "jovana@gmail.com",
                            UserType = "Patient"
                        },
                        new
                        {
                            Id = "p9",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "fixed-guid-1",
                            Email = "stefan@gmail.com",
                            EmailConfirmed = false,
                            FirstName = "Stefan",
                            LastName = "Đorđević",
                            LockoutEnabled = true,
                            NormalizedEmail = "STEFAN@GMAIL.COM",
                            NormalizedUserName = "STEFAN@GMAIL.COM",
                            PhoneNumber = "061100111",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "fixed-guid-2",
                            TwoFactorEnabled = false,
                            UserName = "stefan@gmail.com",
                            UserType = "Patient"
                        },
                        new
                        {
                            Id = "p10",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "fixed-guid-1",
                            Email = "milica@gmail.com",
                            EmailConfirmed = false,
                            FirstName = "Milica",
                            LastName = "Radić",
                            LockoutEnabled = true,
                            NormalizedEmail = "MILICA@GMAIL.COM",
                            NormalizedUserName = "MILICA@GMAIL.COM",
                            PhoneNumber = "061100112",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "fixed-guid-2",
                            TwoFactorEnabled = false,
                            UserName = "milica@gmail.com",
                            UserType = "Patient"
                        },
                        new
                        {
                            Id = "p11",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "fixed-guid-1",
                            Email = "luka@gmail.com",
                            EmailConfirmed = false,
                            FirstName = "Luka",
                            LastName = "Stefanović",
                            LockoutEnabled = true,
                            NormalizedEmail = "LUKA@GMAIL.COM",
                            NormalizedUserName = "LUKA@GMAIL.COM",
                            PhoneNumber = "061100113",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "fixed-guid-2",
                            TwoFactorEnabled = false,
                            UserName = "luka@gmail.com",
                            UserType = "Patient"
                        },
                        new
                        {
                            Id = "p12",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "fixed-guid-1",
                            Email = "teodora@gmail.com",
                            EmailConfirmed = false,
                            FirstName = "Teodora",
                            LastName = "Lazić",
                            LockoutEnabled = true,
                            NormalizedEmail = "TEODORA@GMAIL.COM",
                            NormalizedUserName = "TEODORA@GMAIL.COM",
                            PhoneNumber = "061100114",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "fixed-guid-2",
                            TwoFactorEnabled = false,
                            UserName = "teodora@gmail.com",
                            UserType = "Patient"
                        });
                });

            modelBuilder.Entity("eBolnicaAPI.Models.Entities.Doctor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AppUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("BirthDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LicenseNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RegistrationStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Specialization")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AppUserId")
                        .IsUnique();

                    b.ToTable("Doctors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "Address1",
                            AppUserId = "d1",
                            BirthDate = new DateTime(1995, 3, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Marko",
                            LastName = "Marković",
                            LicenseNumber = "L1",
                            PhoneNumber = "061100100",
                            RegistrationStatus = "Approved",
                            Specialization = "Cardiology"
                        },
                        new
                        {
                            Id = 2,
                            Address = "Address2",
                            AppUserId = "d2",
                            BirthDate = new DateTime(1993, 3, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Senad",
                            LastName = "Husić",
                            LicenseNumber = "L2",
                            PhoneNumber = "061100101",
                            RegistrationStatus = "Approved",
                            Specialization = "Neurology"
                        },
                        new
                        {
                            Id = 3,
                            Address = "Address3",
                            AppUserId = "d3",
                            BirthDate = new DateTime(1991, 3, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Petar",
                            LastName = "Petrović",
                            LicenseNumber = "L3",
                            PhoneNumber = "061100102",
                            RegistrationStatus = "Approved",
                            Specialization = "Psychiatry"
                        });
                });

            modelBuilder.Entity("eBolnicaAPI.Models.Entities.MedicalRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("PatientId")
                        .HasColumnType("int");

                    b.Property<string>("RecordNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("PatientId")
                        .IsUnique();

                    b.ToTable("MedicalRecords");
                });

            modelBuilder.Entity("eBolnicaAPI.Models.Entities.MedicalReport", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Diagnosis")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DoctorId")
                        .HasColumnType("int");

                    b.Property<int>("MedicalRecordId")
                        .HasColumnType("int");

                    b.Property<string>("Symptoms")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Therapy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DoctorId");

                    b.HasIndex("MedicalRecordId");

                    b.ToTable("MedicalReports");
                });

            modelBuilder.Entity("eBolnicaAPI.Models.Entities.Patient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AppUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("BloodType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DoctorId")
                        .HasColumnType("int");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gender")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("IsAdmitted")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MedicalRecordId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AppUserId")
                        .IsUnique();

                    b.HasIndex("DoctorId");

                    b.ToTable("Patients");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "Address1",
                            AppUserId = "p1",
                            BloodType = "A+",
                            DateOfBirth = new DateTime(1990, 3, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DoctorId = 1,
                            FirstName = "Ismet",
                            Gender = "Male",
                            LastName = "Horo",
                            MedicalRecordId = "MRID1",
                            PhoneNumber = "061100103"
                        },
                        new
                        {
                            Id = 2,
                            Address = "Address2",
                            AppUserId = "p2",
                            BloodType = "B+",
                            DateOfBirth = new DateTime(1991, 3, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DoctorId = 1,
                            FirstName = "Elon",
                            Gender = "Female",
                            LastName = "Musk",
                            MedicalRecordId = "MRID2",
                            PhoneNumber = "061100104"
                        },
                        new
                        {
                            Id = 3,
                            Address = "Address3",
                            AppUserId = "p3",
                            BloodType = "AB+",
                            DateOfBirth = new DateTime(1992, 3, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DoctorId = 1,
                            FirstName = "Peter",
                            Gender = "Other",
                            LastName = "Griffin",
                            MedicalRecordId = "MRID3",
                            PhoneNumber = "061100105"
                        },
                        new
                        {
                            Id = 4,
                            Address = "Bulevar Kralja Aleksandra 15",
                            AppUserId = "p4",
                            BloodType = "O+",
                            DateOfBirth = new DateTime(1988, 5, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DoctorId = 1,
                            FirstName = "Ana",
                            Gender = "Female",
                            LastName = "Jovanović",
                            MedicalRecordId = "MRID4",
                            PhoneNumber = "061100106"
                        },
                        new
                        {
                            Id = 5,
                            Address = "Knez Mihailova 25",
                            AppUserId = "p5",
                            BloodType = "A-",
                            DateOfBirth = new DateTime(1985, 7, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DoctorId = 2,
                            FirstName = "Marko",
                            Gender = "Male",
                            LastName = "Nikolić",
                            MedicalRecordId = "MRID5",
                            PhoneNumber = "061100107"
                        },
                        new
                        {
                            Id = 6,
                            Address = "Nemanjina 10",
                            AppUserId = "p6",
                            BloodType = "B-",
                            DateOfBirth = new DateTime(1993, 9, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DoctorId = 2,
                            FirstName = "Sara",
                            Gender = "Female",
                            LastName = "Stojanović",
                            MedicalRecordId = "MRID6",
                            PhoneNumber = "061100108"
                        },
                        new
                        {
                            Id = 7,
                            Address = "Terazije 5",
                            AppUserId = "p7",
                            BloodType = "O-",
                            DateOfBirth = new DateTime(1987, 11, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DoctorId = 2,
                            FirstName = "Nikola",
                            Gender = "Male",
                            LastName = "Popović",
                            MedicalRecordId = "MRID7",
                            PhoneNumber = "061100109"
                        },
                        new
                        {
                            Id = 8,
                            Address = "Vračar 20",
                            AppUserId = "p8",
                            BloodType = "AB-",
                            DateOfBirth = new DateTime(1994, 12, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DoctorId = 3,
                            FirstName = "Jovana",
                            Gender = "Female",
                            LastName = "Milošević",
                            MedicalRecordId = "MRID8",
                            PhoneNumber = "061100110"
                        },
                        new
                        {
                            Id = 9,
                            Address = "Svetog Save 45",
                            AppUserId = "p9",
                            BloodType = "A+",
                            DateOfBirth = new DateTime(1989, 2, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DoctorId = 1,
                            FirstName = "Stefan",
                            Gender = "Male",
                            LastName = "Đorđević",
                            MedicalRecordId = "MRID9",
                            PhoneNumber = "061100111"
                        },
                        new
                        {
                            Id = 10,
                            Address = "Kralja Milana 30",
                            AppUserId = "p10",
                            BloodType = "B+",
                            DateOfBirth = new DateTime(1995, 6, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DoctorId = 1,
                            FirstName = "Milica",
                            Gender = "Female",
                            LastName = "Radić",
                            MedicalRecordId = "MRID10",
                            PhoneNumber = "061100112"
                        },
                        new
                        {
                            Id = 11,
                            Address = "Obilićev venac 12",
                            AppUserId = "p11",
                            BloodType = "O+",
                            DateOfBirth = new DateTime(1986, 8, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DoctorId = 1,
                            FirstName = "Luka",
                            Gender = "Male",
                            LastName = "Stefanović",
                            MedicalRecordId = "MRID11",
                            PhoneNumber = "061100113"
                        },
                        new
                        {
                            Id = 12,
                            Address = "Dunavska 8",
                            AppUserId = "p12",
                            BloodType = "AB+",
                            DateOfBirth = new DateTime(1996, 4, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DoctorId = 1,
                            FirstName = "Teodora",
                            Gender = "Female",
                            LastName = "Lazić",
                            MedicalRecordId = "MRID12",
                            PhoneNumber = "061100114"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("eBolnicaAPI.Models.Entities.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("eBolnicaAPI.Models.Entities.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("eBolnicaAPI.Models.Entities.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("eBolnicaAPI.Models.Entities.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("eBolnicaAPI.Models.Entities.Doctor", b =>
                {
                    b.HasOne("eBolnicaAPI.Models.Entities.AppUser", "AppUser")
                        .WithOne("Doctor")
                        .HasForeignKey("eBolnicaAPI.Models.Entities.Doctor", "AppUserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("AppUser");
                });

            modelBuilder.Entity("eBolnicaAPI.Models.Entities.MedicalRecord", b =>
                {
                    b.HasOne("eBolnicaAPI.Models.Entities.Patient", "Patient")
                        .WithOne("MedicalRecord")
                        .HasForeignKey("eBolnicaAPI.Models.Entities.MedicalRecord", "PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("eBolnicaAPI.Models.Entities.MedicalReport", b =>
                {
                    b.HasOne("eBolnicaAPI.Models.Entities.Doctor", "Doctor")
                        .WithMany()
                        .HasForeignKey("DoctorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("eBolnicaAPI.Models.Entities.MedicalRecord", "MedicalRecord")
                        .WithMany("Reports")
                        .HasForeignKey("MedicalRecordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Doctor");

                    b.Navigation("MedicalRecord");
                });

            modelBuilder.Entity("eBolnicaAPI.Models.Entities.Patient", b =>
                {
                    b.HasOne("eBolnicaAPI.Models.Entities.AppUser", "AppUser")
                        .WithOne("Patient")
                        .HasForeignKey("eBolnicaAPI.Models.Entities.Patient", "AppUserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("eBolnicaAPI.Models.Entities.Doctor", "Doctor")
                        .WithMany("Patients")
                        .HasForeignKey("DoctorId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("AppUser");

                    b.Navigation("Doctor");
                });

            modelBuilder.Entity("eBolnicaAPI.Models.Entities.AppUser", b =>
                {
                    b.Navigation("Doctor");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("eBolnicaAPI.Models.Entities.Doctor", b =>
                {
                    b.Navigation("Patients");
                });

            modelBuilder.Entity("eBolnicaAPI.Models.Entities.MedicalRecord", b =>
                {
                    b.Navigation("Reports");
                });

            modelBuilder.Entity("eBolnicaAPI.Models.Entities.Patient", b =>
                {
                    b.Navigation("MedicalRecord")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
