// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using eBolnicaAPI.Data;

#nullable disable

namespace eBolnicaAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260327214559_SeedDatabase")]
    partial class SeedDatabase
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("eBolnicaAPI.Models.Entities.AppUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LicenseNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("UserType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "a1",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "a0b1c2d3-e4f5-4001-8001-000000000001",
                            Email = "admin@gmail.com",
                            EmailConfirmed = true,
                            FirstName = "Admin",
                            LastName = "User",
                            LockoutEnabled = true,
                            NormalizedEmail = "ADMIN@GMAIL.COM",
                            NormalizedUserName = "ADMIN@GMAIL.COM",
                            PhoneNumber = "061000000",
                            PhoneNumberConfirmed = true,
                            SecurityStamp = "a0b1c2d3-e4f5-4001-8002-000000000001",
                            TwoFactorEnabled = false,
                            UserName = "admin@gmail.com",
                            UserType = "Admin"
                        },
                        new
                        {
                            Id = "d1",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "a0b1c2d3-e4f5-4002-8001-000000000002",
                            Email = "marko@gmail.com",
                            EmailConfirmed = false,
                            FirstName = "Marko",
                            LastName = "Marković",
                            LicenseNumber = "L1",
                            LockoutEnabled = true,
                            NormalizedEmail = "MARKO@GMAIL.COM",
                            NormalizedUserName = "MARKO@GMAIL.COM",
                            PhoneNumber = "061100100",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "a0b1c2d3-e4f5-4002-8002-000000000002",
                            TwoFactorEnabled = false,
                            UserName = "marko@gmail.com",
                            UserType = "Doctor"
                        },
                        new
                        {
                            Id = "d2",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "a0b1c2d3-e4f5-4003-8001-000000000003",
                            Email = "senad@gmail.com",
                            EmailConfirmed = false,
                            FirstName = "Senad",
                            LastName = "Husić",
                            LicenseNumber = "L2",
                            LockoutEnabled = true,
                            NormalizedEmail = "SENAD@GMAIL.COM",
                            NormalizedUserName = "SENAD@GMAIL.COM",
                            PhoneNumber = "061100101",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "a0b1c2d3-e4f5-4003-8002-000000000003",
                            TwoFactorEnabled = false,
                            UserName = "senad@gmail.com",
                            UserType = "Doctor"
                        },
                        new
                        {
                            Id = "d3",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "a0b1c2d3-e4f5-4004-8001-000000000004",
                            Email = "petar@gmail.com",
                            EmailConfirmed = false,
                            FirstName = "Petar",
                            LastName = "Petrović",
                            LicenseNumber = "L3",
                            LockoutEnabled = true,
                            NormalizedEmail = "PETAR@GMAIL.COM",
                            NormalizedUserName = "PETAR@GMAIL.COM",
                            PhoneNumber = "061100102",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "a0b1c2d3-e4f5-4004-8002-000000000004",
                            TwoFactorEnabled = false,
                            UserName = "petar@gmail.com",
                            UserType = "Doctor"
                        },
                        new
                        {
                            Id = "p1",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "a0b1c2d3-e4f5-4005-8001-000000000005",
                            Email = "ismet@gmail.com",
                            EmailConfirmed = false,
                            FirstName = "Ismet",
                            LastName = "Horo",
                            LockoutEnabled = true,
                            NormalizedEmail = "ISMET@GMAIL.COM",
                            NormalizedUserName = "ISMET@GMAIL.COM",
                            PhoneNumber = "061100103",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "a0b1c2d3-e4f5-4005-8002-000000000005",
                            TwoFactorEnabled = false,
                            UserName = "ismet@gmail.com",
                            UserType = "Patient"
                        },
                        new
                        {
                            Id = "p2",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "a0b1c2d3-e4f5-4006-8001-000000000006",
                            Email = "elon@gmail.com",
                            EmailConfirmed = false,
                            FirstName = "Elon",
                            LastName = "Musk",
                            LockoutEnabled = true,
                            NormalizedEmail = "ELON@GMAIL.COM",
                            NormalizedUserName = "ELON@GMAIL.COM",
                            PhoneNumber = "061100104",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "a0b1c2d3-e4f5-4006-8002-000000000006",
                            TwoFactorEnabled = false,
                            UserName = "elon@gmail.com",
                            UserType = "Patient"
                        },
                        new
                        {
                            Id = "p3",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "a0b1c2d3-e4f5-4007-8001-000000000007",
                            Email = "peter@gmail.com",
                            EmailConfirmed = false,
                            FirstName = "Peter",
                            LastName = "Griffin",
                            LockoutEnabled = true,
                            NormalizedEmail = "PETER@GMAIL.COM",
                            NormalizedUserName = "PETER@GMAIL.COM",
                            PhoneNumber = "061100105",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "a0b1c2d3-e4f5-4007-8002-000000000007",
                            TwoFactorEnabled = false,
                            UserName = "peter@gmail.com",
                            UserType = "Patient"
                        },
                        new
                        {
                            Id = "p4",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "a0b1c2d3-e4f5-4008-8001-000000000008",
                            Email = "ana@gmail.com",
                            EmailConfirmed = false,
                            FirstName = "Ana",
                            LastName = "Jovanović",
                            LockoutEnabled = true,
                            NormalizedEmail = "ANA@GMAIL.COM",
                            NormalizedUserName = "ANA@GMAIL.COM",
                            PhoneNumber = "061100106",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "a0b1c2d3-e4f5-4008-8002-000000000008",
                            TwoFactorEnabled = false,
                            UserName = "ana@gmail.com",
                            UserType = "Patient"
                        },
                        new
                        {
                            Id = "p5",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "a0b1c2d3-e4f5-4009-8001-000000000009",
                            Email = "marko.patient@gmail.com",
                            EmailConfirmed = false,
                            FirstName = "Marko",
                            LastName = "Nikolić",
                            LockoutEnabled = true,
                            NormalizedEmail = "MARKO.PATIENT@GMAIL.COM",
                            NormalizedUserName = "MARKO.PATIENT@GMAIL.COM",
                            PhoneNumber = "061100107",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "a0b1c2d3-e4f5-4009-8002-000000000009",
                            TwoFactorEnabled = false,
                            UserName = "marko.patient@gmail.com",
                            UserType = "Patient"
                        },
                        new
                        {
                            Id = "p6",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "a0b1c2d3-e4f5-4010-8001-000000000010",
                            Email = "sara@gmail.com",
                            EmailConfirmed = false,
                            FirstName = "Sara",
                            LastName = "Stojanović",
                            LockoutEnabled = true,
                            NormalizedEmail = "SARA@GMAIL.COM",
                            NormalizedUserName = "SARA@GMAIL.COM",
                            PhoneNumber = "061100108",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "a0b1c2d3-e4f5-4010-8002-000000000010",
                            TwoFactorEnabled = false,
                            UserName = "sara@gmail.com",
                            UserType = "Patient"
                        },
                        new
                        {
                            Id = "p7",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "a0b1c2d3-e4f5-4011-8001-000000000011",
                            Email = "nikola@gmail.com",
                            EmailConfirmed = false,
                            FirstName = "Nikola",
                            LastName = "Popović",
                            LockoutEnabled = true,
                            NormalizedEmail = "NIKOLA@GMAIL.COM",
                            NormalizedUserName = "NIKOLA@GMAIL.COM",
                            PhoneNumber = "061100109",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "a0b1c2d3-e4f5-4011-8002-000000000011",
                            TwoFactorEnabled = false,
                            UserName = "nikola@gmail.com",
                            UserType = "Patient"
                        },
                        new
                        {
                            Id = "p8",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "a0b1c2d3-e4f5-4012-8001-000000000012",
                            Email = "jovana@gmail.com",
                            EmailConfirmed = false,
                            FirstName = "Jovana",
                            LastName = "Milošević",
                            LockoutEnabled = true,
                            NormalizedEmail = "JOVANA@GMAIL.COM",
                            NormalizedUserName = "JOVANA@GMAIL.COM",
                            PhoneNumber = "061100110",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "a0b1c2d3-e4f5-4012-8002-000000000012",
                            TwoFactorEnabled = false,
                            UserName = "jovana@gmail.com",
                            UserType = "Patient"
                        },
                        new
                        {
                            Id = "p9",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "a0b1c2d3-e4f5-4013-8001-000000000013",
                            Email = "stefan@gmail.com",
                            EmailConfirmed = false,
                            FirstName = "Stefan",
                            LastName = "Đorđević",
                            LockoutEnabled = true,
                            NormalizedEmail = "STEFAN@GMAIL.COM",
                            NormalizedUserName = "STEFAN@GMAIL.COM",
                            PhoneNumber = "061100111",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "a0b1c2d3-e4f5-4013-8002-000000000013",
                            TwoFactorEnabled = false,
                            UserName = "stefan@gmail.com",
                            UserType = "Patient"
                        },
                        new
                        {
                            Id = "p10",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "a0b1c2d3-e4f5-4014-8001-000000000014",
                            Email = "milica@gmail.com",
                            EmailConfirmed = false,
                            FirstName = "Milica",
                            LastName = "Radić",
                            LockoutEnabled = true,
                            NormalizedEmail = "MILICA@GMAIL.COM",
                            NormalizedUserName = "MILICA@GMAIL.COM",
                            PhoneNumber = "061100112",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "a0b1c2d3-e4f5-4014-8002-000000000014",
                            TwoFactorEnabled = false,
                            UserName = "milica@gmail.com",
                            UserType = "Patient"
                        },
                        new
                        {
                            Id = "p11",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "a0b1c2d3-e4f5-4015-8001-000000000015",
                            Email = "luka@gmail.com",
                            EmailConfirmed = false,
                            FirstName = "Luka",
                            LastName = "Stefanović",
                            LockoutEnabled = true,
                            NormalizedEmail = "LUKA@GMAIL.COM",
                            NormalizedUserName = "LUKA@GMAIL.COM",
                            PhoneNumber = "061100113",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "a0b1c2d3-e4f5-4015-8002-000000000015",
                            TwoFactorEnabled = false,
                            UserName = "luka@gmail.com",
                            UserType = "Patient"
                        },
                        new
                        {
                            Id = "p12",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "a0b1c2d3-e4f5-4016-8001-000000000016",
                            Email = "teodora@gmail.com",
                            EmailConfirmed = false,
                            FirstName = "Teodora",
                            LastName = "Lazić",
                            LockoutEnabled = true,
                            NormalizedEmail = "TEODORA@GMAIL.COM",
                            NormalizedUserName = "TEODORA@GMAIL.COM",
                            PhoneNumber = "061100114",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "a0b1c2d3-e4f5-4016-8002-000000000016",
                            TwoFactorEnabled = false,
                            UserName = "teodora@gmail.com",
                            UserType = "Patient"
                        },
                        new
                        {
                            Id = "ph1",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "a0b1c2d3-e4f5-4017-8001-000000000017",
                            Email = "pharmacist@pharmacy.com",
                            EmailConfirmed = false,
                            FirstName = "Milan",
                            LastName = "Jovanović",
                            LicenseNumber = "PH-L1",
                            LockoutEnabled = true,
                            NormalizedEmail = "PHARMACIST@PHARMACY.COM",
                            NormalizedUserName = "PHARMACIST@PHARMACY.COM",
                            PhoneNumber = "061200200",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "a0b1c2d3-e4f5-4017-8002-000000000017",
                            TwoFactorEnabled = false,
                            UserName = "pharmacist@pharmacy.com",
                            UserType = "Pharmacist"
                        });
                });

            modelBuilder.Entity("eBolnicaAPI.Models.Entities.Doctor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AppUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("BirthDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gender")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LicenseNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RegistrationStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Specialization")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AppUserId")
                        .IsUnique();

                    b.ToTable("Doctors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "Address1",
                            AppUserId = "d1",
                            BirthDate = new DateTime(1995, 3, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Marko",
                            Gender = "Male",
                            LastName = "Marković",
                            LicenseNumber = "L1",
                            PhoneNumber = "061100100",
                            RegistrationStatus = "Approved",
                            Specialization = "Cardiology"
                        },
                        new
                        {
                            Id = 2,
                            Address = "Address2",
                            AppUserId = "d2",
                            BirthDate = new DateTime(1993, 3, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Senad",
                            Gender = "Male",
                            LastName = "Husić",
                            LicenseNumber = "L2",
                            PhoneNumber = "061100101",
                            RegistrationStatus = "Approved",
                            Specialization = "Neurology"
                        },
                        new
                        {
                            Id = 3,
                            Address = "Address3",
                            AppUserId = "d3",
                            BirthDate = new DateTime(1991, 3, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Petar",
                            Gender = "Male",
                            LastName = "Petrović",
                            LicenseNumber = "L3",
                            PhoneNumber = "061100102",
                            RegistrationStatus = "Approved",
                            Specialization = "Psychiatry"
                        });
                });

            modelBuilder.Entity("eBolnicaAPI.Models.Entities.FileEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("FileSize")
                        .HasColumnType("bigint");

                    b.Property<int>("PatientId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("PatientId");

                    b.ToTable("Files");
                });

            modelBuilder.Entity("eBolnicaAPI.Models.Entities.MedicalRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("PatientId")
                        .HasColumnType("int");

                    b.Property<string>("RecordNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("PatientId")
                        .IsUnique();

                    b.ToTable("MedicalRecords");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            PatientId = 1,
                            RecordNumber = "MRID1"
                        },
                        new
                        {
                            Id = 2,
                            PatientId = 2,
                            RecordNumber = "MRID2"
                        },
                        new
                        {
                            Id = 3,
                            PatientId = 3,
                            RecordNumber = "MRID3"
                        },
                        new
                        {
                            Id = 4,
                            PatientId = 4,
                            RecordNumber = "MRID4"
                        },
                        new
                        {
                            Id = 5,
                            PatientId = 5,
                            RecordNumber = "MRID5"
                        },
                        new
                        {
                            Id = 6,
                            PatientId = 6,
                            RecordNumber = "MRID6"
                        },
                        new
                        {
                            Id = 7,
                            PatientId = 7,
                            RecordNumber = "MRID7"
                        },
                        new
                        {
                            Id = 8,
                            PatientId = 8,
                            RecordNumber = "MRID8"
                        },
                        new
                        {
                            Id = 9,
                            PatientId = 9,
                            RecordNumber = "MRID9"
                        },
                        new
                        {
                            Id = 10,
                            PatientId = 10,
                            RecordNumber = "MRID10"
                        },
                        new
                        {
                            Id = 11,
                            PatientId = 11,
                            RecordNumber = "MRID11"
                        },
                        new
                        {
                            Id = 12,
                            PatientId = 12,
                            RecordNumber = "MRID12"
                        });
                });

            modelBuilder.Entity("eBolnicaAPI.Models.Entities.MedicalReport", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Diagnosis")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DoctorId")
                        .HasColumnType("int");

                    b.Property<int>("MedicalRecordId")
                        .HasColumnType("int");

                    b.Property<string>("Symptoms")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Therapy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DoctorId");

                    b.HasIndex("MedicalRecordId");

                    b.ToTable("MedicalReports");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 10, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Diagnosis = "Tension headache",
                            DoctorId = 1,
                            MedicalRecordId = 1,
                            Symptoms = "Headache, fatigue",
                            Therapy = "Rest, Paracetamol 500mg"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2025, 11, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Diagnosis = "Hypertension",
                            DoctorId = 1,
                            MedicalRecordId = 1,
                            Symptoms = "High blood pressure",
                            Therapy = "Amlodipine 5mg"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2025, 12, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Diagnosis = "Anxiety",
                            DoctorId = 1,
                            MedicalRecordId = 1,
                            Symptoms = "Chest pain",
                            Therapy = "Relaxation techniques"
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2026, 1, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Diagnosis = "Iron deficiency",
                            DoctorId = 1,
                            MedicalRecordId = 1,
                            Symptoms = "Fatigue, dizziness",
                            Therapy = "Iron supplements"
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2025, 10, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Diagnosis = "Pharyngitis",
                            DoctorId = 1,
                            MedicalRecordId = 2,
                            Symptoms = "Sore throat, fever",
                            Therapy = "Amoxicillin 500mg"
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2025, 11, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Diagnosis = "Common cold",
                            DoctorId = 1,
                            MedicalRecordId = 2,
                            Symptoms = "Cough, runny nose",
                            Therapy = "Rest, fluids"
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2026, 1, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Diagnosis = "Lumbar strain",
                            DoctorId = 1,
                            MedicalRecordId = 2,
                            Symptoms = "Back pain",
                            Therapy = "Ibuprofen 400mg, physiotherapy"
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2026, 2, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Diagnosis = "Gastroenteritis",
                            DoctorId = 1,
                            MedicalRecordId = 2,
                            Symptoms = "Nausea, vomiting",
                            Therapy = "Hydration, bland diet"
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTime(2025, 9, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Diagnosis = "Arthritis",
                            DoctorId = 1,
                            MedicalRecordId = 3,
                            Symptoms = "Joint pain, swelling",
                            Therapy = "Diclofenac 50mg"
                        },
                        new
                        {
                            Id = 10,
                            CreatedAt = new DateTime(2025, 11, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Diagnosis = "Mild asthma",
                            DoctorId = 1,
                            MedicalRecordId = 3,
                            Symptoms = "Shortness of breath",
                            Therapy = "Inhaler prescribed"
                        },
                        new
                        {
                            Id = 11,
                            CreatedAt = new DateTime(2026, 1, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Diagnosis = "Allergic reaction",
                            DoctorId = 1,
                            MedicalRecordId = 3,
                            Symptoms = "Skin rash, itching",
                            Therapy = "Cetirizine 10mg"
                        },
                        new
                        {
                            Id = 12,
                            CreatedAt = new DateTime(2026, 2, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Diagnosis = "Stress-related insomnia",
                            DoctorId = 1,
                            MedicalRecordId = 3,
                            Symptoms = "Insomnia, anxiety",
                            Therapy = "Relaxation therapy"
                        },
                        new
                        {
                            Id = 13,
                            CreatedAt = new DateTime(2025, 10, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Diagnosis = "Type 2 Diabetes",
                            DoctorId = 1,
                            MedicalRecordId = 4,
                            Symptoms = "Frequent urination, thirst",
                            Therapy = "Metformin 500mg"
                        },
                        new
                        {
                            Id = 14,
                            CreatedAt = new DateTime(2025, 11, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Diagnosis = "Hyperlipidemia",
                            DoctorId = 1,
                            MedicalRecordId = 4,
                            Symptoms = "High cholesterol",
                            Therapy = "Atorvastatin 20mg"
                        },
                        new
                        {
                            Id = 15,
                            CreatedAt = new DateTime(2026, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Diagnosis = "Diabetic check-up",
                            DoctorId = 1,
                            MedicalRecordId = 4,
                            Symptoms = "Blurred vision",
                            Therapy = "Continue Metformin"
                        },
                        new
                        {
                            Id = 16,
                            CreatedAt = new DateTime(2026, 2, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Diagnosis = "Thyroid check",
                            DoctorId = 1,
                            MedicalRecordId = 4,
                            Symptoms = "Weight gain, fatigue",
                            Therapy = "Blood tests ordered"
                        },
                        new
                        {
                            Id = 17,
                            CreatedAt = new DateTime(2025, 10, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Diagnosis = "Migraine",
                            DoctorId = 2,
                            MedicalRecordId = 5,
                            Symptoms = "Migraine, light sensitivity",
                            Therapy = "Paracetamol, dark room rest"
                        },
                        new
                        {
                            Id = 18,
                            CreatedAt = new DateTime(2025, 11, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Diagnosis = "Carpal tunnel syndrome",
                            DoctorId = 2,
                            MedicalRecordId = 5,
                            Symptoms = "Numbness in hands",
                            Therapy = "Wrist splint, rest"
                        },
                        new
                        {
                            Id = 19,
                            CreatedAt = new DateTime(2026, 1, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Diagnosis = "Stress-related cognitive issues",
                            DoctorId = 2,
                            MedicalRecordId = 5,
                            Symptoms = "Memory issues, confusion",
                            Therapy = "Stress management"
                        },
                        new
                        {
                            Id = 20,
                            CreatedAt = new DateTime(2026, 2, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Diagnosis = "Vertigo",
                            DoctorId = 2,
                            MedicalRecordId = 5,
                            Symptoms = "Dizziness, nausea",
                            Therapy = "Epley maneuver"
                        },
                        new
                        {
                            Id = 21,
                            CreatedAt = new DateTime(2025, 9, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Diagnosis = "Otitis media",
                            DoctorId = 2,
                            MedicalRecordId = 6,
                            Symptoms = "Ear pain, hearing loss",
                            Therapy = "Amoxicillin 500mg"
                        },
                        new
                        {
                            Id = 22,
                            CreatedAt = new DateTime(2025, 11, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Diagnosis = "Conjunctivitis",
                            DoctorId = 2,
                            MedicalRecordId = 6,
                            Symptoms = "Eye redness, discharge",
                            Therapy = "Antibiotic eye drops"
                        },
                        new
                        {
                            Id = 23,
                            CreatedAt = new DateTime(2026, 1, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Diagnosis = "Grade 1 sprain",
                            DoctorId = 2,
                            MedicalRecordId = 6,
                            Symptoms = "Ankle sprain",
                            Therapy = "RICE method, Ibuprofen"
                        },
                        new
                        {
                            Id = 24,
                            CreatedAt = new DateTime(2026, 2, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Diagnosis = "IBS",
                            DoctorId = 2,
                            MedicalRecordId = 6,
                            Symptoms = "Stomach cramps",
                            Therapy = "Diet modification"
                        },
                        new
                        {
                            Id = 25,
                            CreatedAt = new DateTime(2025, 10, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Diagnosis = "Costochondritis",
                            DoctorId = 2,
                            MedicalRecordId = 7,
                            Symptoms = "Chest tightness",
                            Therapy = "Anti-inflammatory medication"
                        },
                        new
                        {
                            Id = 26,
                            CreatedAt = new DateTime(2025, 12, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Diagnosis = "Osteoarthritis",
                            DoctorId = 2,
                            MedicalRecordId = 7,
                            Symptoms = "Knee pain, stiffness",
                            Therapy = "Physiotherapy, Diclofenac"
                        },
                        new
                        {
                            Id = 27,
                            CreatedAt = new DateTime(2026, 1, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Diagnosis = "Vitamin D deficiency",
                            DoctorId = 2,
                            MedicalRecordId = 7,
                            Symptoms = "Hair loss, fatigue",
                            Therapy = "Vitamin D3 supplements"
                        },
                        new
                        {
                            Id = 28,
                            CreatedAt = new DateTime(2026, 2, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Diagnosis = "GERD",
                            DoctorId = 2,
                            MedicalRecordId = 7,
                            Symptoms = "Acid reflux, heartburn",
                            Therapy = "Omeprazole 20mg"
                        },
                        new
                        {
                            Id = 29,
                            CreatedAt = new DateTime(2025, 10, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Diagnosis = "Anxiety disorder",
                            DoctorId = 3,
                            MedicalRecordId = 8,
                            Symptoms = "Mood swings, irritability",
                            Therapy = "Therapy sessions"
                        },
                        new
                        {
                            Id = 30,
                            CreatedAt = new DateTime(2025, 11, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Diagnosis = "Depression",
                            DoctorId = 3,
                            MedicalRecordId = 8,
                            Symptoms = "Sleep problems, fatigue",
                            Therapy = "CBT therapy"
                        },
                        new
                        {
                            Id = 31,
                            CreatedAt = new DateTime(2026, 1, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Diagnosis = "Panic disorder",
                            DoctorId = 3,
                            MedicalRecordId = 8,
                            Symptoms = "Panic attacks",
                            Therapy = "Breathing exercises"
                        },
                        new
                        {
                            Id = 32,
                            CreatedAt = new DateTime(2026, 2, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Diagnosis = "Social anxiety",
                            DoctorId = 3,
                            MedicalRecordId = 8,
                            Symptoms = "Social withdrawal",
                            Therapy = "Exposure therapy"
                        });
                });

            modelBuilder.Entity("eBolnicaAPI.Models.Entities.Medication", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BatchNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Category")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DosageForm")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ExpiryDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("GenericName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Manufacturer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MinimumStockLevel")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("RequiresPrescription")
                        .HasColumnType("bit");

                    b.Property<int>("StockQuantity")
                        .HasColumnType("int");

                    b.Property<string>("Strength")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Category")
                        .HasDatabaseName("IX_Medications_Category");

                    b.HasIndex("ExpiryDate")
                        .HasDatabaseName("IX_Medications_ExpiryDate");

                    b.HasIndex("Name");

                    b.HasIndex("StockQuantity")
                        .HasDatabaseName("IX_Medications_StockQuantity");

                    b.HasIndex("Category", "IsActive")
                        .HasDatabaseName("IX_Medications_Category_IsActive");

                    b.HasIndex("IsActive", "CreatedAt")
                        .HasDatabaseName("IX_Medications_IsActive_CreatedAt");

                    b.HasIndex("Name", "Category")
                        .HasDatabaseName("IX_Medications_Name_Category");

                    b.HasIndex("Price", "StockQuantity")
                        .HasDatabaseName("IX_Medications_Price_StockQuantity");

                    b.ToTable("Medications");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BatchNumber = "BATCH-001",
                            Category = "Painkillers",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Pain reliever and fever reducer",
                            DosageForm = "Tablet",
                            ExpiryDate = new DateTime(2026, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GenericName = "Acetaminophen",
                            IsActive = true,
                            Manufacturer = "PharmaCorp",
                            MinimumStockLevel = 100,
                            Name = "Paracetamol",
                            Price = 250.00m,
                            RequiresPrescription = false,
                            StockQuantity = 500,
                            Strength = "500mg"
                        },
                        new
                        {
                            Id = 2,
                            BatchNumber = "BATCH-002",
                            Category = "Painkillers",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Nonsteroidal anti-inflammatory drug",
                            DosageForm = "Tablet",
                            ExpiryDate = new DateTime(2026, 6, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GenericName = "Ibuprofen",
                            IsActive = true,
                            Manufacturer = "MediPharm",
                            MinimumStockLevel = 80,
                            Name = "Ibuprofen",
                            Price = 320.00m,
                            RequiresPrescription = false,
                            StockQuantity = 350,
                            Strength = "400mg"
                        },
                        new
                        {
                            Id = 3,
                            BatchNumber = "BATCH-003",
                            Category = "Antibiotics",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Antibiotic for bacterial infections",
                            DosageForm = "Capsule",
                            ExpiryDate = new DateTime(2025, 9, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GenericName = "Amoxicillin",
                            IsActive = true,
                            Manufacturer = "AntibioPharm",
                            MinimumStockLevel = 50,
                            Name = "Amoxicillin",
                            Price = 850.00m,
                            RequiresPrescription = true,
                            StockQuantity = 200,
                            Strength = "500mg"
                        },
                        new
                        {
                            Id = 4,
                            BatchNumber = "BATCH-004",
                            Category = "Painkillers",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Pain reliever, anti-inflammatory, and blood thinner",
                            DosageForm = "Tablet",
                            ExpiryDate = new DateTime(2027, 3, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GenericName = "Acetylsalicylic acid",
                            IsActive = true,
                            Manufacturer = "PharmaCorp",
                            MinimumStockLevel = 50,
                            Name = "Aspirin",
                            Price = 180.00m,
                            RequiresPrescription = false,
                            StockQuantity = 45,
                            Strength = "100mg"
                        },
                        new
                        {
                            Id = 5,
                            BatchNumber = "BATCH-005",
                            Category = "Antihistamines",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Antihistamine for allergies",
                            DosageForm = "Tablet",
                            ExpiryDate = new DateTime(2026, 8, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GenericName = "Cetirizine",
                            IsActive = true,
                            Manufacturer = "AllergyMed",
                            MinimumStockLevel = 60,
                            Name = "Cetirizine",
                            Price = 420.00m,
                            RequiresPrescription = false,
                            StockQuantity = 280,
                            Strength = "10mg"
                        },
                        new
                        {
                            Id = 6,
                            BatchNumber = "BATCH-006",
                            Category = "Gastrointestinal",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Proton pump inhibitor for acid reflux",
                            DosageForm = "Capsule",
                            ExpiryDate = new DateTime(2025, 11, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GenericName = "Omeprazole",
                            IsActive = true,
                            Manufacturer = "DigestPharm",
                            MinimumStockLevel = 40,
                            Name = "Omeprazole",
                            Price = 650.00m,
                            RequiresPrescription = true,
                            StockQuantity = 150,
                            Strength = "20mg"
                        },
                        new
                        {
                            Id = 7,
                            BatchNumber = "BATCH-007",
                            Category = "Antidiabetic",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Antidiabetic medication",
                            DosageForm = "Tablet",
                            ExpiryDate = new DateTime(2026, 4, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GenericName = "Metformin",
                            IsActive = true,
                            Manufacturer = "DiabetPharm",
                            MinimumStockLevel = 30,
                            Name = "Metformin",
                            Price = 550.00m,
                            RequiresPrescription = true,
                            StockQuantity = 120,
                            Strength = "500mg"
                        },
                        new
                        {
                            Id = 8,
                            BatchNumber = "BATCH-008",
                            Category = "Antihistamines",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Antihistamine for seasonal allergies",
                            DosageForm = "Tablet",
                            ExpiryDate = new DateTime(2026, 7, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GenericName = "Loratadine",
                            IsActive = true,
                            Manufacturer = "AllergyMed",
                            MinimumStockLevel = 70,
                            Name = "Loratadine",
                            Price = 380.00m,
                            RequiresPrescription = false,
                            StockQuantity = 320,
                            Strength = "10mg"
                        },
                        new
                        {
                            Id = 9,
                            BatchNumber = "BATCH-009",
                            Category = "Antibiotics",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Broad-spectrum antibiotic",
                            DosageForm = "Tablet",
                            ExpiryDate = new DateTime(2025, 10, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GenericName = "Azithromycin",
                            IsActive = true,
                            Manufacturer = "AntibioPharm",
                            MinimumStockLevel = 25,
                            Name = "Azithromycin",
                            Price = 1200.00m,
                            RequiresPrescription = true,
                            StockQuantity = 80,
                            Strength = "500mg"
                        },
                        new
                        {
                            Id = 10,
                            BatchNumber = "BATCH-010",
                            Category = "Vitamins",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Vitamin D supplement",
                            DosageForm = "Capsule",
                            ExpiryDate = new DateTime(2027, 1, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GenericName = "Cholecalciferol",
                            IsActive = true,
                            Manufacturer = "VitaminsPlus",
                            MinimumStockLevel = 150,
                            Name = "Vitamin D3",
                            Price = 450.00m,
                            RequiresPrescription = false,
                            StockQuantity = 600,
                            Strength = "2000 IU"
                        },
                        new
                        {
                            Id = 11,
                            BatchNumber = "BATCH-011",
                            Category = "Antibiotics",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Fluoroquinolone antibiotic",
                            DosageForm = "Tablet",
                            ExpiryDate = new DateTime(2025, 8, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GenericName = "Ciprofloxacin",
                            IsActive = true,
                            Manufacturer = "AntibioPharm",
                            MinimumStockLevel = 20,
                            Name = "Ciprofloxacin",
                            Price = 950.00m,
                            RequiresPrescription = true,
                            StockQuantity = 35,
                            Strength = "500mg"
                        },
                        new
                        {
                            Id = 12,
                            BatchNumber = "BATCH-012",
                            Category = "Painkillers",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "NSAID for pain and inflammation",
                            DosageForm = "Tablet",
                            ExpiryDate = new DateTime(2026, 5, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GenericName = "Diclofenac",
                            IsActive = true,
                            Manufacturer = "MediPharm",
                            MinimumStockLevel = 45,
                            Name = "Diclofenac",
                            Price = 520.00m,
                            RequiresPrescription = true,
                            StockQuantity = 180,
                            Strength = "50mg"
                        },
                        new
                        {
                            Id = 13,
                            BatchNumber = "BATCH-013",
                            Category = "Antihistamines",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Antihistamine for allergies",
                            DosageForm = "Tablet",
                            ExpiryDate = new DateTime(2026, 9, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GenericName = "Fexofenadine",
                            IsActive = true,
                            Manufacturer = "AllergyMed",
                            MinimumStockLevel = 55,
                            Name = "Fexofenadine",
                            Price = 480.00m,
                            RequiresPrescription = false,
                            StockQuantity = 250,
                            Strength = "120mg"
                        },
                        new
                        {
                            Id = 14,
                            BatchNumber = "BATCH-014",
                            Category = "Supplements",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Calcium supplement and antacid",
                            DosageForm = "Tablet",
                            ExpiryDate = new DateTime(2027, 2, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GenericName = "Calcium Carbonate",
                            IsActive = true,
                            Manufacturer = "VitaminsPlus",
                            MinimumStockLevel = 100,
                            Name = "Calcium Carbonate",
                            Price = 280.00m,
                            RequiresPrescription = false,
                            StockQuantity = 400,
                            Strength = "500mg"
                        },
                        new
                        {
                            Id = 15,
                            BatchNumber = "BATCH-015",
                            Category = "Cardiovascular",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Cholesterol-lowering medication",
                            DosageForm = "Tablet",
                            ExpiryDate = new DateTime(2026, 11, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GenericName = "Atorvastatin",
                            IsActive = true,
                            Manufacturer = "CardioPharm",
                            MinimumStockLevel = 25,
                            Name = "Atorvastatin",
                            Price = 1100.00m,
                            RequiresPrescription = true,
                            StockQuantity = 95,
                            Strength = "20mg"
                        });
                });

            modelBuilder.Entity("eBolnicaAPI.Models.Entities.Patient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AppUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("BloodType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DoctorId")
                        .HasColumnType("int");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gender")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("IsAdmitted")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RegistrationStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AppUserId")
                        .IsUnique();

                    b.HasIndex("DoctorId");

                    b.ToTable("Patients");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "Address1",
                            AppUserId = "p1",
                            BloodType = "A+",
                            DateOfBirth = new DateTime(1990, 3, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DoctorId = 1,
                            FirstName = "Ismet",
                            Gender = "Male",
                            LastName = "Horo",
                            PhoneNumber = "061100103",
                            RegistrationStatus = "Pending"
                        },
                        new
                        {
                            Id = 2,
                            Address = "Address2",
                            AppUserId = "p2",
                            BloodType = "B+",
                            DateOfBirth = new DateTime(1991, 3, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DoctorId = 1,
                            FirstName = "Elon",
                            Gender = "Female",
                            LastName = "Musk",
                            PhoneNumber = "061100104",
                            RegistrationStatus = "Pending"
                        },
                        new
                        {
                            Id = 3,
                            Address = "Address3",
                            AppUserId = "p3",
                            BloodType = "AB+",
                            DateOfBirth = new DateTime(1992, 3, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DoctorId = 1,
                            FirstName = "Peter",
                            Gender = "Other",
                            LastName = "Griffin",
                            PhoneNumber = "061100105",
                            RegistrationStatus = "Pending"
                        },
                        new
                        {
                            Id = 4,
                            Address = "Bulevar Kralja Aleksandra 15",
                            AppUserId = "p4",
                            BloodType = "O+",
                            DateOfBirth = new DateTime(1988, 5, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DoctorId = 1,
                            FirstName = "Ana",
                            Gender = "Female",
                            LastName = "Jovanović",
                            PhoneNumber = "061100106",
                            RegistrationStatus = "Pending"
                        },
                        new
                        {
                            Id = 5,
                            Address = "Knez Mihailova 25",
                            AppUserId = "p5",
                            BloodType = "A-",
                            DateOfBirth = new DateTime(1985, 7, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DoctorId = 2,
                            FirstName = "Marko",
                            Gender = "Male",
                            LastName = "Nikolić",
                            PhoneNumber = "061100107",
                            RegistrationStatus = "Pending"
                        },
                        new
                        {
                            Id = 6,
                            Address = "Nemanjina 10",
                            AppUserId = "p6",
                            BloodType = "B-",
                            DateOfBirth = new DateTime(1993, 9, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DoctorId = 2,
                            FirstName = "Sara",
                            Gender = "Female",
                            LastName = "Stojanović",
                            PhoneNumber = "061100108",
                            RegistrationStatus = "Pending"
                        },
                        new
                        {
                            Id = 7,
                            Address = "Terazije 5",
                            AppUserId = "p7",
                            BloodType = "O-",
                            DateOfBirth = new DateTime(1987, 11, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DoctorId = 2,
                            FirstName = "Nikola",
                            Gender = "Male",
                            LastName = "Popović",
                            PhoneNumber = "061100109",
                            RegistrationStatus = "Pending"
                        },
                        new
                        {
                            Id = 8,
                            Address = "Vračar 20",
                            AppUserId = "p8",
                            BloodType = "AB-",
                            DateOfBirth = new DateTime(1994, 12, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DoctorId = 3,
                            FirstName = "Jovana",
                            Gender = "Female",
                            LastName = "Milošević",
                            PhoneNumber = "061100110",
                            RegistrationStatus = "Pending"
                        },
                        new
                        {
                            Id = 9,
                            Address = "Svetog Save 45",
                            AppUserId = "p9",
                            BloodType = "A+",
                            DateOfBirth = new DateTime(1989, 2, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DoctorId = 1,
                            FirstName = "Stefan",
                            Gender = "Male",
                            LastName = "Đorđević",
                            PhoneNumber = "061100111",
                            RegistrationStatus = "Pending"
                        },
                        new
                        {
                            Id = 10,
                            Address = "Kralja Milana 30",
                            AppUserId = "p10",
                            BloodType = "B+",
                            DateOfBirth = new DateTime(1995, 6, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DoctorId = 1,
                            FirstName = "Milica",
                            Gender = "Female",
                            LastName = "Radić",
                            PhoneNumber = "061100112",
                            RegistrationStatus = "Pending"
                        },
                        new
                        {
                            Id = 11,
                            Address = "Obilićev venac 12",
                            AppUserId = "p11",
                            BloodType = "O+",
                            DateOfBirth = new DateTime(1986, 8, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DoctorId = 1,
                            FirstName = "Luka",
                            Gender = "Male",
                            LastName = "Stefanović",
                            PhoneNumber = "061100113",
                            RegistrationStatus = "Pending"
                        },
                        new
                        {
                            Id = 12,
                            Address = "Dunavska 8",
                            AppUserId = "p12",
                            BloodType = "AB+",
                            DateOfBirth = new DateTime(1996, 4, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DoctorId = 1,
                            FirstName = "Teodora",
                            Gender = "Female",
                            LastName = "Lazić",
                            PhoneNumber = "061100114",
                            RegistrationStatus = "Pending"
                        });
                });

            modelBuilder.Entity("eBolnicaAPI.Models.Entities.Pharmacist", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AppUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("HireDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LicenseNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("AppUserId")
                        .IsUnique();

                    b.HasIndex("LicenseNumber")
                        .IsUnique();

                    b.ToTable("Pharmacists");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "Apotekarska 15, Beograd",
                            AppUserId = "ph1",
                            CreatedAt = new DateTime(2020, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Milan",
                            HireDate = new DateTime(2020, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Jovanović",
                            LicenseNumber = "PH-L1",
                            PhoneNumber = "061200200"
                        });
                });

            modelBuilder.Entity("eBolnicaAPI.Models.Entities.Prescription", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DispensedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("DoctorId")
                        .HasColumnType("int");

                    b.Property<int>("MedicalReportId")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PatientId")
                        .HasColumnType("int");

                    b.Property<int?>("PharmacistId")
                        .HasColumnType("int");

                    b.Property<DateTime>("PrescribedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PrescriptionNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("DoctorId")
                        .HasDatabaseName("IX_Prescriptions_DoctorId");

                    b.HasIndex("MedicalReportId");

                    b.HasIndex("PharmacistId");

                    b.HasIndex("PrescribedDate")
                        .HasDatabaseName("IX_Prescriptions_PrescribedDate");

                    b.HasIndex("PrescriptionNumber")
                        .IsUnique();

                    b.HasIndex("PatientId", "Status")
                        .HasDatabaseName("IX_Prescriptions_PatientId_Status");

                    b.HasIndex("Status", "CreatedAt")
                        .HasDatabaseName("IX_Prescriptions_Status_CreatedAt");

                    b.HasIndex("Status", "DispensedDate")
                        .HasDatabaseName("IX_Prescriptions_Status_DispensedDate");

                    b.ToTable("Prescriptions");
                });

            modelBuilder.Entity("eBolnicaAPI.Models.Entities.PrescriptionItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Instructions")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MedicationId")
                        .HasColumnType("int");

                    b.Property<int>("PrescriptionId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("MedicationId")
                        .HasDatabaseName("IX_PrescriptionItems_MedicationId");

                    b.HasIndex("PrescriptionId", "MedicationId")
                        .HasDatabaseName("IX_PrescriptionItems_PrescriptionId_MedicationId");

                    b.ToTable("PrescriptionItems");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("eBolnicaAPI.Models.Entities.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("eBolnicaAPI.Models.Entities.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("eBolnicaAPI.Models.Entities.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("eBolnicaAPI.Models.Entities.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("eBolnicaAPI.Models.Entities.Doctor", b =>
                {
                    b.HasOne("eBolnicaAPI.Models.Entities.AppUser", "AppUser")
                        .WithOne("Doctor")
                        .HasForeignKey("eBolnicaAPI.Models.Entities.Doctor", "AppUserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("AppUser");
                });

            modelBuilder.Entity("eBolnicaAPI.Models.Entities.FileEntity", b =>
                {
                    b.HasOne("eBolnicaAPI.Models.Entities.Patient", "Patient")
                        .WithMany("Files")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("eBolnicaAPI.Models.Entities.MedicalRecord", b =>
                {
                    b.HasOne("eBolnicaAPI.Models.Entities.Patient", "Patient")
                        .WithOne("MedicalRecord")
                        .HasForeignKey("eBolnicaAPI.Models.Entities.MedicalRecord", "PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("eBolnicaAPI.Models.Entities.MedicalReport", b =>
                {
                    b.HasOne("eBolnicaAPI.Models.Entities.Doctor", "Doctor")
                        .WithMany()
                        .HasForeignKey("DoctorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("eBolnicaAPI.Models.Entities.MedicalRecord", "MedicalRecord")
                        .WithMany("MedicalReports")
                        .HasForeignKey("MedicalRecordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Doctor");

                    b.Navigation("MedicalRecord");
                });

            modelBuilder.Entity("eBolnicaAPI.Models.Entities.Patient", b =>
                {
                    b.HasOne("eBolnicaAPI.Models.Entities.AppUser", "AppUser")
                        .WithOne("Patient")
                        .HasForeignKey("eBolnicaAPI.Models.Entities.Patient", "AppUserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("eBolnicaAPI.Models.Entities.Doctor", "Doctor")
                        .WithMany("Patients")
                        .HasForeignKey("DoctorId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("AppUser");

                    b.Navigation("Doctor");
                });

            modelBuilder.Entity("eBolnicaAPI.Models.Entities.Pharmacist", b =>
                {
                    b.HasOne("eBolnicaAPI.Models.Entities.AppUser", "AppUser")
                        .WithOne("Pharmacist")
                        .HasForeignKey("eBolnicaAPI.Models.Entities.Pharmacist", "AppUserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("AppUser");
                });

            modelBuilder.Entity("eBolnicaAPI.Models.Entities.Prescription", b =>
                {
                    b.HasOne("eBolnicaAPI.Models.Entities.Doctor", "Doctor")
                        .WithMany()
                        .HasForeignKey("DoctorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("eBolnicaAPI.Models.Entities.MedicalReport", "MedicalReport")
                        .WithMany()
                        .HasForeignKey("MedicalReportId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("eBolnicaAPI.Models.Entities.Patient", "Patient")
                        .WithMany()
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("eBolnicaAPI.Models.Entities.Pharmacist", "Pharmacist")
                        .WithMany("DispensedPrescriptions")
                        .HasForeignKey("PharmacistId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Doctor");

                    b.Navigation("MedicalReport");

                    b.Navigation("Patient");

                    b.Navigation("Pharmacist");
                });

            modelBuilder.Entity("eBolnicaAPI.Models.Entities.PrescriptionItem", b =>
                {
                    b.HasOne("eBolnicaAPI.Models.Entities.Medication", "Medication")
                        .WithMany("PrescriptionItems")
                        .HasForeignKey("MedicationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("eBolnicaAPI.Models.Entities.Prescription", "Prescription")
                        .WithMany("PrescriptionItems")
                        .HasForeignKey("PrescriptionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Medication");

                    b.Navigation("Prescription");
                });

            modelBuilder.Entity("eBolnicaAPI.Models.Entities.AppUser", b =>
                {
                    b.Navigation("Doctor");

                    b.Navigation("Patient");

                    b.Navigation("Pharmacist");
                });

            modelBuilder.Entity("eBolnicaAPI.Models.Entities.Doctor", b =>
                {
                    b.Navigation("Patients");
                });

            modelBuilder.Entity("eBolnicaAPI.Models.Entities.MedicalRecord", b =>
                {
                    b.Navigation("MedicalReports");
                });

            modelBuilder.Entity("eBolnicaAPI.Models.Entities.Medication", b =>
                {
                    b.Navigation("PrescriptionItems");
                });

            modelBuilder.Entity("eBolnicaAPI.Models.Entities.Patient", b =>
                {
                    b.Navigation("Files");

                    b.Navigation("MedicalRecord")
                        .IsRequired();
                });

            modelBuilder.Entity("eBolnicaAPI.Models.Entities.Pharmacist", b =>
                {
                    b.Navigation("DispensedPrescriptions");
                });

            modelBuilder.Entity("eBolnicaAPI.Models.Entities.Prescription", b =>
                {
                    b.Navigation("PrescriptionItems");
                });
#pragma warning restore 612, 618
        }
    }
}
